#!/bin/bash

echo "Setting up environment..."
echo ""
echo "Installing dependencies"
sudo apt-get update
sudo apt-get install -y build-essential software-properties-common python-dev python-pip python3-dev python3-pip curl cmake

read -n1 -p "Install tmux? [y/n] " tmux
read -n1 -p "Install vim (next question is neovim)? [y/n] " vim
read -n1 -p "Install neovim? [y/n] " nvim
read -n1 -p "Install ranger? [y/n] " ranger
read -n1 -p "Install zsh? [y/n] " zsh
read -n1 -p "Install docker? [y/n] " docker
read -n1 -p "Install rbenv? [y/n] " rbenv


# Copy across my gitconfig
ln -s ~/genesis/configs/.gitconfig ~/.gitconfig

# Copy my scripts folder (maybe symlink this instead)
#cp -R ./.scripts ~/

