# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.

# confirmations, etc.) must go above this block; everything else may go below.

#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# autoload -Uz compinit
# compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
# setopt autocd extendedglob notify
# unsetopt beep
# bindkey -v
# End of lines configured by zsh-newuser-install

# Path to your oh-my-zsh installation.
# TODO: Set this path up in the installation!
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"
# ZSH_THEME="powerlevel10k/powerlevel10k"
# POWERLEVEL10K_MODE="nerdfont-complete"
# POWERLEVEL10K_RIGHT_PROMPT_ELEMENTS=(ram)

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(
  git
  bundler
  zsh-syntax-highlighting
  zsh-autosuggestions
  tmuxinator
)

source $ZSH/oh-my-zsh.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias deathfm="mplayer http://hi5.death.fm"
alias classical="mplayer http://cms.stream.publicradio.org/cms.mp3"
alias weather="curl wttr.in"
alias reload="clear && omz reload"
alias cls="clear"
alias dc="docker compose"
alias ll="ls -lAh"

export PATH="$HOME/.local/bin:$PATH"

export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")

export VISUAL=nvim
export EDITOR="$VISUAL"
export XDG_DATA_DIRS="/snap/bin:$XDG_DATA_DIRS"
export MYVIMRC="~/.config/nvim/init.vim"
export DISABLE_AUTO_TITLE=true

alias vim="nvim"
alias vi="nvim"
alias tm="~/.bin/tm"
alias mux="tmuxinator"
alias dev="cd ~/dev"
alias jb="cd ~/dev/brazenbraden/jugglebee"
alias cop="gh copilot explain"

# sudo apt install bat
alias cat="batcat"

set -o vi

# -------------------
# DOCKER CONFIGS
# -------------------
alias dc="docker compose"
alias docker_prune="docker rmi $(docker images --filter dangling=true -q --no-trunc)"
# -------------------

# RBENV CONFIG
# --------------------
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init -)"
# --------------------

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. "$HOME/.atuin/bin/env"

eval "$(atuin init zsh)"
