#!/bin/bash

echo "Installing neovim.."

sudo apt-get install software-properties-common

sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install -y neovim python-dev python-pip python3-dev python3-pip

pip3 install --user neovim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.config/nvim

ln -s ~/genesis/configs/.vimrc ~/.config/nvim/init.vim

echo "alias vim=nvim" >> ~/.zshrc
echo "export EDITOR=nvim" >> ~/.zshrc
export VISUAL=nvim
export EDITOR="$VISUAL"
export XDG_DATA_DIRS="/snap/bin:$XDG_DATA_DIRS"
export MYVIMRC="~/.config/nvim/init.vim"
export FZF_DEFAULT_COMMAND='rg --files --hidden --smartcase --glob "!.git/*"'
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
echo "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh" >> ~/.zshrc

echo "Post-install notes:"
echo "--------------------"
echo "1. run :PlugInstall when you first start vim"
echo "2. run ~/.config/nvim/plugged/YouCompleteMe/install.py"
echo "Enjoy!"
