#!/bin/bash

echo "Installing rbenv.."
sudo apt update
sudo apt install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build


# todo: find what terminal config to use (.bashrc or .zshrc or whatever)
terminal_config=~/.zshrc
echo "RBENV CONFIG" >> $terminal_config
echo "--------------------" >> $terminal_config
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $terminal_config
echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' >> $terminal_config
echo 'eval "$(~/.rbenv/bin/rbenv init - zsh)"' >> $terminal_config
echo "--------------------" >> $terminal_config

read -p "What ruby version do you want to install? " version
rbenv install $version
rbenv global $version
