#!/bin/bash

rm  ~/.tmux.conf
rm -rf ~/.tmux

sudo apt-get update -y
sudo apt-get install -y tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -s $(pwd)/configs/.tmux.conf ~/.tmux.conf
