#!/bin/bash

echo "Installing tmux.."

sudo apt-get update
sudo apt-get install -y tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -s ~/genesis/configs/.tmux.conf ~/.tmux.conf
