#!/bin/bash

echo "Installing vim.."

sudo apt-get update
sudo apt-get install -y vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -s ~/genesis/configs/.vimrc ~/.vimrc

echo "export EDITOR=vim" >> ~/.zshrc
echo "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh" >> ~/.zshrc

echo "Post-install notes:"
echo "--------------------"
echo "1. run :PlugInstall when you first start vim"
echo "2. run ~/.vim/plugged/YouCompleteMe/install.py"
echo "Enjoy!"
