# inherit_from: ../.rubocop.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
