# Lis of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-online-status'

# Rebind ctrl+b to ctrl+a
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Bind "r" to reload the .tmux.config after making changes
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Speed things up
set -sg escape-time 10
set -sg repeat-time 600

# Increase history limit
set -g history-limit 5000

# Window and pane configuring
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on
set -g set-titles on

# Save and restore sessions after reboot
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'

# New key bindings
setw -g mode-keys vi
bind | split-window -h
bind - split-window -v

# Create ~/.tmux.conf.local to override this file
if '[ -f ~/.tmux.conf.osx ]' 'source ~/.tmux.conf.osx'
if '[ -f ~/.tmux.conf.nix ]' 'source ~/.tmux.conf.nix'

# Set theme
set -g @themepack 'powerline/block/cyan'

# Battery and Online indicators
set -g status-right 'Online: #{online_status} | #{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '
set -g status-left 'sausages!'

# Custom Keymappings
unbind-key 'C-\'

# Remap tmux leader : to leader ;
# unbind ;
# unbind-key :
# bind-key ; :

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run -b '~/.tmux/plugins/tpm/tpm'

